version: "3"

services:
    backend:
        build:
            context: backend
        ports:
            - 8000:8000
        volumes:
            - ./backend:/app
        command: >
            sh -c "python manage.py run 0.0.0.0:8000"